name: top_story_nyt
description: A new Flutter project for bab almoda company flutter_test.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image:
  connectivity_plus:
  dartz:
  easy_localization: ^3.0.3
  equatable:
  flutter_bloc:
  get_it:
  http:
  lottie:
  responsive_sizer:
  shimmer:
  shared_preferences: ^2.2.2
  mime: ^1.0.4
  http_parser: ^4.0.2
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  mockito: ^5.4.2
  mocktail: ^1.0.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/shared/
    - assets/image/news/
    - assets/icon/
    - assets/icon/news/
    - assets/icon/shared/
    - assets/lottie/
    - assets/lottie/shared/
    - assets/lottie/news/
    - assets/translations/
    - assets/video/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/font/Cairo-Light.ttf
          weight: 300
        - asset: assets/font/Cairo-Regular.otf
          weight: 400
        - asset: assets/font/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/font/Cairo-Bold.ttf
          weight: 700
